version: "3"
services:
  api:
    build: '.'
    working_dir: /home/node/app
    environment:
      - NODE_ENV=production
    networks:
      - mongo-nw
    ports:
      - 8000:80

networks:
  mongo-nw:
    external: true
